"""
doc_generator.py — Office-file generator tool for Sovereign.

Generates real deliverable files from structured agent output:
  - DOCX: Approval notes, reports, memos
  - PPTX: Presentation slides (findings, summaries)
  - XLSX: Data tables, calculation sheets

All templates are self-contained (no internet required).
Files are saved to settings.output_dir and returned as a path.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from loguru import logger
from pydantic import BaseModel

from config import settings

# ── Word (DOCX) ───────────────────────────────────────────────────────────────
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

# ── PowerPoint (PPTX) ────────────────────────────────────────────────────────
from pptx import Presentation
from pptx.util import Inches as PInches, Pt as PPt
from pptx.dml.color import RGBColor as PRGBColor
from pptx.enum.text import PP_ALIGN

# ── Excel (XLSX) ──────────────────────────────────────────────────────────────
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ── Colour palette ─────────────────────────────────────────────────────────────
_SOVEREIGN_BLUE   = PRGBColor(0x1A, 0x1A, 0x2E)
_SOVEREIGN_ACCENT = PRGBColor(0x00, 0xD4, 0xAA)
_WHITE            = PRGBColor(0xFF, 0xFF, 0xFF)


# ══════════════════════════════════════════════════════════════════════════════
#  DOCX templates
# ══════════════════════════════════════════════════════════════════════════════

def _docx_approval_note(doc: Document, content: dict) -> None:
    """Approval Note — used for inspection-report approvals."""
    header = doc.sections[0].header
    hp = header.paragraphs[0]
    hp.text = "SOVEREIGN — CONFIDENTIAL"
    hp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    hp.runs[0].font.size = Pt(8)
    hp.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    title_para = doc.add_heading(content.get("title", "Approval Note"), level=1)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta_table = doc.add_table(rows=4, cols=2)
    meta_table.style = "Table Grid"
    for i, (label, value) in enumerate([
        ("Reference No.", content.get("ref_no", "SV-" + datetime.now().strftime("%Y%m%d-%H%M"))),
        ("Date",          content.get("date", datetime.now().strftime("%B %d, %Y"))),
        ("Prepared By",   content.get("prepared_by", "Sovereign AI Agent")),
        ("Access Level",  content.get("access_level", "public").upper()),
    ]):
        meta_table.cell(i, 0).text = label
        meta_table.cell(i, 1).text = value
        meta_table.cell(i, 0).paragraphs[0].runs[0].bold = True
    doc.add_paragraph()

    doc.add_heading("Executive Summary", level=2)
    doc.add_paragraph(content.get("summary", ""))

    if content.get("findings"):
        doc.add_heading("Key Findings", level=2)
        for f in content["findings"]:
            doc.add_paragraph(f, style="List Bullet")

    if content.get("sources"):
        doc.add_heading("Source Documents Referenced", level=2)
        for s in content["sources"]:
            doc.add_paragraph(s, style="List Bullet")

    if content.get("recommendation"):
        doc.add_heading("Recommendation / Decision", level=2)
        p = doc.add_paragraph(content["recommendation"])
        p.runs[0].bold = True

    doc.add_paragraph()
    doc.add_paragraph("Approved by: ________________________")
    doc.add_paragraph("Signature:   ________________________")
    doc.add_paragraph(f"Date:        {content.get('date', datetime.now().strftime('%B %d, %Y'))}")

    footer = doc.sections[0].footer
    fp = footer.paragraphs[0]
    fp.text = "Generated by Sovereign AI Workbench — Air-gapped, on-device only."
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fp.runs[0].font.size = Pt(7)
    fp.runs[0].font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)


def _docx_generic_report(doc: Document, content: dict) -> None:
    """Generic report template."""
    doc.add_heading(content.get("title", "Report"), level=1)
    doc.add_paragraph(f"Date: {content.get('date', datetime.now().strftime('%B %d, %Y'))}")
    doc.add_paragraph(f"Author: {content.get('author', 'Sovereign AI')}")
    doc.add_paragraph()
    if content.get("summary"):
        doc.add_heading("Executive Summary", level=2)
        doc.add_paragraph(content["summary"])
    for section in content.get("sections", []):
        doc.add_heading(section.get("heading", ""), level=2)
        body = section.get("body", "")
        if isinstance(body, list):
            for item in body:
                doc.add_paragraph(str(item), style="List Bullet")
        else:
            doc.add_paragraph(str(body))
    if content.get("conclusion"):
        doc.add_heading("Conclusion", level=2)
        doc.add_paragraph(content["conclusion"])


DOCX_TEMPLATES = {
    "approval_note":     _docx_approval_note,
    "generic_report":    _docx_generic_report,
    "inspection_report": _docx_generic_report,
}


def generate_docx(template: str, content: dict[str, Any], filename: str | None = None) -> Path:
    """Generate a .docx file from a named template + content dict."""
    if template not in DOCX_TEMPLATES:
        template = "generic_report"
    doc = Document()
    doc.styles["Normal"].font.name = "Calibri"
    doc.styles["Normal"].font.size = Pt(11)
    DOCX_TEMPLATES[template](doc, content)
    fname = (filename or f"{template}_{datetime.now().strftime('%Y%m%d_%H%M%S')}") + ".docx"
    out_path = settings.output_dir / fname
    doc.save(str(out_path))
    logger.success("Generated DOCX: {}", out_path)
    return out_path


# ══════════════════════════════════════════════════════════════════════════════
#  PPTX templates
# ══════════════════════════════════════════════════════════════════════════════

def _set_slide_bg(slide, color: PRGBColor) -> None:
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _pptx_findings_deck(prs: Presentation, content: dict) -> None:
    """Inspection findings presentation deck — dark themed."""
    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, _SOVEREIGN_BLUE)
    tb = slide.shapes.add_textbox(PInches(1), PInches(2), PInches(8), PInches(1.5))
    tf = tb.text_frame
    tf.word_wrap = True
    p = tf.add_paragraph()
    p.text = content.get("title", "Inspection Findings")
    p.font.size = PPt(40); p.font.bold = True; p.font.color.rgb = _WHITE
    p.alignment = PP_ALIGN.CENTER
    p2 = tf.add_paragraph()
    p2.text = content.get("subtitle", f"Date: {datetime.now().strftime('%B %d, %Y')}")
    p2.font.size = PPt(18); p2.font.color.rgb = _SOVEREIGN_ACCENT
    p2.alignment = PP_ALIGN.CENTER

    # One slide per finding
    for i, finding in enumerate(content.get("findings", []), 1):
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        _set_slide_bg(slide, _SOVEREIGN_BLUE)
        badge = slide.shapes.add_textbox(PInches(0.5), PInches(0.3), PInches(1), PInches(0.5))
        badge.text_frame.text = f"#{i}"
        badge.text_frame.paragraphs[0].font.color.rgb = _SOVEREIGN_ACCENT
        badge.text_frame.paragraphs[0].font.size = PPt(14)
        hb = slide.shapes.add_textbox(PInches(0.5), PInches(0.8), PInches(9), PInches(1))
        hb.text_frame.word_wrap = True
        hp = hb.text_frame.add_paragraph()
        hp.text = finding.get("heading", f"Finding {i}")
        hp.font.size = PPt(26); hp.font.bold = True; hp.font.color.rgb = _WHITE
        bb = slide.shapes.add_textbox(PInches(0.5), PInches(2), PInches(9), PInches(3.5))
        bb.text_frame.word_wrap = True
        bp = bb.text_frame.add_paragraph()
        bp.text = finding.get("body", "")
        bp.font.size = PPt(16); bp.font.color.rgb = _WHITE

    # Closing slide
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, _SOVEREIGN_BLUE)
    tb = slide.shapes.add_textbox(PInches(1), PInches(2.5), PInches(8), PInches(1))
    p = tb.text_frame.add_paragraph()
    p.text = "Sovereign AI Workbench — 100% On-Device"
    p.font.size = PPt(20); p.font.color.rgb = _SOVEREIGN_ACCENT
    p.alignment = PP_ALIGN.CENTER


PPTX_TEMPLATES = {
    "findings_deck": _pptx_findings_deck,
    "briefing":      _pptx_findings_deck,
}


def generate_pptx(template: str, content: dict[str, Any], filename: str | None = None) -> Path:
    """Generate a .pptx file from a named template + content dict."""
    if template not in PPTX_TEMPLATES:
        template = "findings_deck"
    prs = Presentation()
    prs.slide_width = PInches(10)
    prs.slide_height = PInches(5.625)
    PPTX_TEMPLATES[template](prs, content)
    fname = (filename or f"{template}_{datetime.now().strftime('%Y%m%d_%H%M%S')}") + ".pptx"
    out_path = settings.output_dir / fname
    prs.save(str(out_path))
    logger.success("Generated PPTX: {}", out_path)
    return out_path


# ══════════════════════════════════════════════════════════════════════════════
#  XLSX templates
# ══════════════════════════════════════════════════════════════════════════════

_HEADER_FILL  = PatternFill("solid", fgColor="1A1A2E")
_ACCENT_FILL  = PatternFill("solid", fgColor="00D4AA")
_ALT_ROW_FILL = PatternFill("solid", fgColor="F0F7F4")
_HEADER_FONT  = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
_BODY_FONT    = Font(name="Calibri", size=10)
_CENTER       = Alignment(horizontal="center", vertical="center", wrap_text=True)
_LEFT         = Alignment(horizontal="left",   vertical="center", wrap_text=True)
_THIN = Border(
    left=Side(style="thin", color="CCCCCC"), right=Side(style="thin",  color="CCCCCC"),
    top=Side(style="thin",  color="CCCCCC"), bottom=Side(style="thin", color="CCCCCC"),
)


def _xlsx_data_table(wb: openpyxl.Workbook, content: dict) -> None:
    ws = wb.active
    ws.title = content.get("sheet_title", "Data")
    headers = content.get("headers", [])
    rows    = content.get("rows", [])

    # Title row
    end_col = get_column_letter(max(len(headers), 1))
    ws.merge_cells(f"A1:{end_col}1")
    c = ws["A1"]
    c.value = content.get("title", "Data Table")
    c.font  = Font(name="Calibri", bold=True, size=14, color="FFFFFF")
    c.fill  = _HEADER_FILL; c.alignment = _CENTER
    ws.row_dimensions[1].height = 30

    for ci, h in enumerate(headers, 1):
        cell = ws.cell(row=2, column=ci, value=h)
        cell.font = _HEADER_FONT; cell.fill = _ACCENT_FILL
        cell.alignment = _CENTER; cell.border = _THIN
    ws.row_dimensions[2].height = 22

    for ri, row in enumerate(rows, 3):
        fill = _ALT_ROW_FILL if ri % 2 == 0 else PatternFill()
        for ci, val in enumerate(row, 1):
            cell = ws.cell(row=ri, column=ci, value=val)
            cell.font = _BODY_FONT; cell.alignment = _LEFT
            cell.border = _THIN
            if ri % 2 == 0:
                cell.fill = fill
        ws.row_dimensions[ri].height = 18

    for ci, h in enumerate(headers, 1):
        col_vals = [str(row[ci-1]) if ci-1 < len(row) else "" for row in rows]
        max_len = max([len(str(h))] + [len(v) for v in col_vals])
        ws.column_dimensions[get_column_letter(ci)].width = min(max_len + 4, 40)

    meta = wb.create_sheet("Metadata")
    meta["A1"] = "Generated By";  meta["B1"] = "Sovereign AI Workbench"
    meta["A2"] = "Generated At";  meta["B2"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    meta["A3"] = "Air-gapped";    meta["B3"] = "Yes — 100% on-device"


def _xlsx_calculation_sheet(wb: openpyxl.Workbook, content: dict) -> None:
    ws = wb.active
    ws.title = content.get("sheet_title", "Calculations")
    ws.merge_cells("A1:D1")
    ws["A1"].value = content.get("title", "Calculation Sheet")
    ws["A1"].font  = Font(name="Calibri", bold=True, size=14, color="FFFFFF")
    ws["A1"].fill  = _HEADER_FILL; ws["A1"].alignment = _CENTER
    ws.row_dimensions[1].height = 30

    ws["A3"].value = "INPUTS"
    ws["A3"].font  = Font(name="Calibri", bold=True, size=11, color="FFFFFF")
    ws["A3"].fill  = _ACCENT_FILL

    inputs = content.get("inputs", [])
    for i, inp in enumerate(inputs, 4):
        ws.cell(row=i, column=1, value=inp.get("label", "")).font  = _BODY_FONT
        ws.cell(row=i, column=2, value=inp.get("value", "")).font  = _BODY_FONT
        ws.cell(row=i, column=3, value=inp.get("unit",  "")).font  = _BODY_FONT

    rs = len(inputs) + 6
    ws.cell(row=rs, column=1, value="RESULTS").font = Font(bold=True, size=11, color="FFFFFF")
    ws.cell(row=rs, column=1).fill = _ACCENT_FILL

    for j, res in enumerate(content.get("results", []), rs + 1):
        ws.cell(row=j, column=1, value=res.get("label", "")).font  = _BODY_FONT
        ws.cell(row=j, column=2, value=res.get("value", "")).font  = Font(bold=True)
        ws.cell(row=j, column=3, value=res.get("unit",  "")).font  = _BODY_FONT

    for col in ["A", "B", "C", "D"]:
        ws.column_dimensions[col].width = 28


XLSX_TEMPLATES = {
    "data_table":        _xlsx_data_table,
    "metrics":           _xlsx_data_table,
    "calculation_sheet": _xlsx_calculation_sheet,
}


def generate_xlsx(template: str, content: dict[str, Any], filename: str | None = None) -> Path:
    """Generate a .xlsx file from a named template + content dict."""
    if template not in XLSX_TEMPLATES:
        template = "data_table"
    wb = openpyxl.Workbook()
    XLSX_TEMPLATES[template](wb, content)
    fname = (filename or f"{template}_{datetime.now().strftime('%Y%m%d_%H%M%S')}") + ".xlsx"
    out_path = settings.output_dir / fname
    wb.save(str(out_path))
    logger.success("Generated XLSX: {}", out_path)
    return out_path


# ══════════════════════════════════════════════════════════════════════════════
#  FastAPI endpoints (agent tool-calling interface)
# ══════════════════════════════════════════════════════════════════════════════

app = FastAPI(title="Sovereign Document Generator", version="1.0.0")


class DocRequest(BaseModel):
    template: str
    content: dict[str, Any]
    filename: str | None = None


@app.post("/generate/docx")
async def api_docx(req: DocRequest):
    try:
        path = generate_docx(req.template, req.content, req.filename)
        return {"status": "ok", "file": str(path), "filename": path.name}
    except ValueError as e:
        raise HTTPException(400, str(e))
    except Exception as e:
        logger.exception("DOCX generation failed")
        raise HTTPException(500, str(e))


@app.post("/generate/pptx")
async def api_pptx(req: DocRequest):
    try:
        path = generate_pptx(req.template, req.content, req.filename)
        return {"status": "ok", "file": str(path), "filename": path.name}
    except ValueError as e:
        raise HTTPException(400, str(e))
    except Exception as e:
        logger.exception("PPTX generation failed")
        raise HTTPException(500, str(e))


@app.post("/generate/xlsx")
async def api_xlsx(req: DocRequest):
    try:
        path = generate_xlsx(req.template, req.content, req.filename)
        return {"status": "ok", "file": str(path), "filename": path.name}
    except ValueError as e:
        raise HTTPException(400, str(e))
    except Exception as e:
        logger.exception("XLSX generation failed")
        raise HTTPException(500, str(e))


@app.get("/generate/download/{filename}")
async def api_download(filename: str):
    file_path = settings.output_dir / filename
    if not file_path.exists():
        raise HTTPException(404, "File not found")
    return FileResponse(str(file_path), filename=filename)


@app.get("/generate/list")
async def api_list():
    files = [
        {"name": f.name, "size_kb": round(f.stat().st_size / 1024, 1)}
        for f in sorted(settings.output_dir.iterdir(), key=lambda x: x.stat().st_mtime, reverse=True)
        if f.is_file()
    ]
    return {"files": files}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("doc_generator:app", host=settings.api_host, port=8002, reload=False)
